# Generated by Django 5.0 on 2023-12-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
