# Generated by Django 5.0 on 2023-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_rank_delete_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='duel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
