# Generated by Django 5.0 on 2023-12-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_duel_time_alter_duel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='stop_time',
            field=models.TimeField(null=True),
        ),
    ]
