# Generated by Django 5.0 on 2023-12-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_duel_stop_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='stop_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
