# Generated by Django 5.0 on 2023-12-08 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_duel_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.round'),
        ),
    ]
