# Generated by Django 5.0 on 2023-12-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_duel_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='main.player'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='main.player'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table'),
        ),
    ]
