# Generated by Django 5.0 on 2023-12-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_duel_live_delete_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default=1, upload_to='images/players'),
            preserve_default=False,
        ),
    ]
