# Generated by Django 5.0 on 2023-12-18 18:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='duel',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='main.player'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='main.player'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.round'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='score1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='duel',
            name='score2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='duel',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table'),
        ),
    ]
